version: '3.4'

services:
  api:
    container_name: api
    command: bash -c "python3 manage.py migrate && python3 manage.py loaddata initial_data.json && python3 manage.py createsuperuser --noinput && python3 manage.py runserver 0.0.0.0:8000"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - lib_nw

  db:
    container_name: db
    image: postgres
    volumes:
      - data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - lib_nw


volumes:
  data:


networks:
  lib_nw:
    driver: bridge
